name = "CartesianGeometry"
uuid = "5961ddb3-e46d-41f1-806c-0197ba873d0b"
authors = ["Vincent Le Chenadec <vincentlechenadec@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CartesianArrays = "76a5a9e6-eaa9-45ad-9e60-9c4e19c8bef4"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Vofinit = "1beee101-8e09-4165-b3f9-a3e33534e38b"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
